### PR TITLE
AC 6676: Horizontally scroll tab sub navigation

### PR DESCRIPTION
**Pull request by freshprincekla**
Changes introduced in [AC-6676](https://masschallenge.atlassian.net/browse/AC-6676):
- Allow horizontal scrolling for sub navigation 

**How to test:**
- Masquerade as [User](https://test6.masschallenge.org/admin/simpleuser/user/43639/masquerade/)
- Head over to [IL finalists](https://test6.masschallenge.org/dashboard/il-finalist/il-finalist-landing-page/)
- Click [Resources](https://test6.masschallenge.org/nav/resources) on the side nav
- You will then see the top sub nav. You can decrease the size of the window and you will see that the sub nav bar doesn't overflow off the screen and it scrollable with a shadow that indicates which side of the nav bar has more scrollable items

**Locally**
- As Admin demoadmin.masschallenge.org
- Go to [fluent pages](http://localhost:8181/admin/fluent_pages/page/261/change/)
- Add sub nav association nodes along with a sub nav item e.g.
 `home_nav` and sub nav item `room booking`
Note: Add several items  to the same node(about 5)
- Masquerade as user(http://localhost:8181/admin/simpleuser/user/11167/masquerade/)
- You will find several sub nav items. You will then see the top sub nav. You can decrease the size of the window and you will see that the sub nav bar doesn't overflow off the screen and it scrollable with a shadow that indicates which side of the nav bar has more scrollable items

### CODE REVIEW

**Comment by VincentHokie** [comment]
QA

**Comment by kaymation** [comment]
Test6 is currently down for me. 502 bad gateway

**Comment by freshprincekla** [comment]
@kaymation something up with the test machine. But it seems to work in  incognito.

**Comment by VincentHokie** [comment]
@kaymation @freshprincekla the problem is a single commit has 3 tags. So travis picks the tag that was created first

Screenshot 2019-06-06 at 13 11 03

I'm going to delete the other tags i.e. `vTR-AC-6676v2` and `vTR-AC-6676` and rerun the `vTR-AC-6676vtest` travis [build](https://travis-ci.org/masschallenge/impact-api/builds/541383474) so that the docker image on AWS is correctly tagged

**Comment by VincentHokie** [comment]
deleted tags with
`make delete-tag tag=vTR-AC-6676v2`
`make delete-tag tag=vTR-AC-6676`

then rerun the build on travis,
test6 is now available

**Comment by kaymation** [comment]
test6 is still down for me
 :(

**Comment by VincentHokie** [comment]
same! 😩 😨 

I could browse just fine...now im really worried about these test machines

**Comment by freshprincekla** [comment]
@VincentHokie and @kaymation it seems to work when in incognito. Not sure why though

**Comment by VincentHokie** [comment]
looks like the issue with test6 is the django-smtp-ssl library, every time a request is made a new relic call is made that requires that package

**Pull request merged**
