### PR TITLE
[AC-7932]: P2: Fix misbehaving CSS due to !important flag

### PR DESCRIPTION
**Pull request by shakirandagire**
Changes introduced in [AC-7932](https://masschallenge.atlassian.net/browse/AC-7932):
- Removed custom styles

**How to test:**

- On this branch and the [sibling PR](https://github.com/masschallenge/accelerate/pull/2759).
- Login as a mentor and visit https://test5.masschallenge.org/newofficehours and create or edit an existing office hour
- Set the end time to be equal to or earlier than the start time so that the UI displays an error
- Notice that the error dropdown style is consistent with the [standard error handling provided by semantic-UI.](https://react.semantic-ui.com/modules/dropdown/#states-error)
- Also notice that the custom CSS has been removed.

### CODE REVIEW

**Comment by geofrocker** [comment]
taking code

**Comment by geofrocker** [comment]
Remove unnecessary commits

**Review by geofrocker — CHANGES_REQUESTED** [review]
Remove unnecessary commits

**Review by iankigen — CHANGES_REQUESTED** [review]
We still have style issues
Screenshot 2020-09-29 at 14 21 17
Screenshot 2020-09-29 at 14 21 46

**Review by iankigen — APPROVED** [review]
QA: LGTM
- Error dropdown style is consistent with the standard error handling provided by semantic-UI ✅ 
- Custom CSS from is removed so the `!important` flag does not cause issues ✅

**Review by geofrocker — APPROVED** [review]
Looks good

**Pull request merged**
