### PR TITLE
AC 6573 Integrate MassChallenge semantic customizations into React/Front-end

### PR DESCRIPTION
**Pull request by freshprincekla**
**Changes introduced in [AC-6573](https://masschallenge.atlassian.net/browse/AC-6573)**
- Converted semantic theme to be an npm package installed from our repo

**`Locally Development`**
- Make sure you are on AC-6573 on the semantic-ui-theme repo, and the frontend repo.
- In the semantic-ui-theme repo run `yarn link` and then run `npm run-script watch`
- in the front-end, delete your `node_modules`
- Run `yarn cache clean` and then `yarn`
- Then repo run `yarn link "semantic-ui-theme"`.
- You can then start build using impact-api
- You can then make changes to the massChallenge theme and it will be reflected in front-end.

**Locally Install the package**
- in the front-end, delete your `node_modules`
- Run `yarn cache clean`
- Run `yarn`
- The package will be installed with the version that has the `latest` tag

**`On Deployment`**
- I added a css property in the semantic-ui-theme repo, `*{background:#000}` that turns the background of everything to black
- Login into accelerate on [test machine 1](https://test1.masschallenge.org/accounts/login/?next=/)
- Head to [people directory](https://test1.masschallenge.org/people)
- You will see that the background is black which shows that its picking from the semantic repo.

### CODE REVIEW

**Comment by VincentHokie** [comment]
shepherding 🐑

**Comment by pbx** [comment]
(Pausing in my review of this while Brian checks to see whether the persistent troubles I'm having can be reproduced by others. E.g. 
```
$ npm install
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> fsevents@1.2.9 install /Users/paulbissex/code/STACK-1/semantic-ui-theme/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/paulbissex/code/STACK-1/semantic-ui-theme/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> semantic-ui@2.4.2 install /Users/paulbissex/code/STACK-1/semantic-ui-theme/node_modules/semantic-ui
> gulp install

fs.js:27
const { Math, Object, Reflect } = primordials;
                                  ^

ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (/Users/paulbissex/code/STACK-1/semantic-ui-theme/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/paulbissex/code/STACK-1/semantic-ui-theme/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/paulbissex/code/STACK-1/semantic-ui-theme/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.4.2 install: `gulp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the semantic-ui@2.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by shanbady** [comment]
@pbx i just ran through the instructions and im not getting the same build issue you are seeing.

**Comment by pbx** [comment]
Yeah @shanbady it seems to be particular to my machine, but we can't figure out what it is. I have the latest `yarn` and `node` versions. @freshprincekla is trying to help sort it out.  Out of curiosity I tried things on my Linux box, and they worked pretty cleanly -- but the problematic `fsevents` package is flagged as not-Linux-compatible, so it doesn't even try installing it, hence sidestepping the install errors I keep seeing.

**Pull request merged**
